(function(root){
const DAY=86400000;
const defaultConfig={purchase:25,place:25,conditional:25,limits:[10,20,35]};
const round=n=>Math.round(n*100)/100;
function intersect(a,b){ const parse=v=>(v||'Desconhecido').toLocaleLowerCase('pt-BR').split(',').map(x=>x.trim()).filter(Boolean);const x=parse(a),y=parse(b);const unknown=x.includes('desconhecido')||y.includes('desconhecido');return {match:unknown||x.includes('todos')||y.includes('todos')||x.some(v=>y.includes(v)),unknown}; }
function rating(score,count,config=defaultConfig){if(!count)return {name:'Sem mecânicas',level:0};let i=config.limits.findIndex(x=>score<=x);if(i<0)i=3;return {name:['Tranquilo','Equilibrado','Arrojado','Sobrecarregado'][i],level:i};}
function calculate(scenario,catalog,config=defaultConfig,excluded=[]){
const from=Date.parse(scenario.start),to=Date.parse(scenario.end);const entries=scenario.items.filter(x=>x.enabled&&!excluded.includes(x.id)).map(x=>({...x,mechanic:catalog.find(c=>c.id===x.mechanicId)})).filter(x=>x.mechanic&&Date.parse(x.start)<=to&&Date.parse(x.end)>=from);
const cuts=new Set([from,to+DAY]);entries.forEach(x=>{cuts.add(Math.max(from,Date.parse(x.start)));cuts.add(Math.min(to+DAY,Date.parse(x.end)+DAY));});const sorted=[...cuts].sort((a,b)=>a-b);const intervals=[];
for(let k=0;k<sorted.length-1;k++){const t=sorted[k];const active=entries.filter(x=>Date.parse(x.start)<=t&&Date.parse(x.end)>=t).map(x=>({...x,load:x.mechanic.complexity*x.mechanic.multiplier}));const pairs=[];
for(let i=0;i<active.length;i++)for(let j=i+1;j<active.length;j++){const a=active[i],b=active[j],aud=intersect(a.audience,b.audience),prod=intersect(a.products,b.products);if(!aud.match||!prod.match)continue;const same=a.places.some(v=>b.places.includes(v));const conditional=[a.cumulative,b.cumulative].some(v=>['Condicional','Desconhecida'].includes(v));const percent=config.purchase+(same?config.place:0)+(conditional?config.conditional:0);pairs.push({a:a.id,b:b.id,names:[a.mechanic.name,b.mechanic.name],same,conditional,unknown:aud.unknown||prod.unknown,load:round(Math.min(a.load,b.load)*percent/100)});}
const base=round(active.reduce((n,x)=>n+x.load,0)),extra=round(pairs.reduce((n,x)=>n+x.load,0));intervals.push({start:new Date(t).toISOString().slice(0,10),end:new Date(sorted[k+1]-DAY).toISOString().slice(0,10),active,pairs:pairs.sort((a,b)=>b.load-a.load),base,extra,score:round(base+extra)});}
const peak=intervals.reduce((best,x)=>x.score>best.score?x:best,intervals[0]||{score:0,base:0,extra:0,active:[],pairs:[],start:scenario.start,end:scenario.end});return {...peak,intervals,rating:rating(peak.score,peak.active.length,config)};
}
function suggestions(s,c,config,target){const current=calculate(s,c,config);const rank={Baixa:0,'Média':1,Alta:2};const candidates=s.items.filter(x=>x.enabled&&!x.essential&&x.start<=s.end&&x.end>=s.start).map(x=>({item:x,result:calculate(s,c,config,[x.id])})).map(x=>({...x,reduction:round(current.score-x.result.score)})).sort((a,b)=>rank[a.item.priority]-rank[b.item.priority]||b.reduction-a.reduction||a.item.id.localeCompare(b.item.id));const excluded=[];let result=current;while(result.score>target){const options=s.items.filter(x=>x.enabled&&!x.essential&&!excluded.includes(x.id)&&x.start<=s.end&&x.end>=s.start).map(x=>({item:x,result:calculate(s,c,config,[...excluded,x.id])})).sort((a,b)=>rank[a.item.priority]-rank[b.item.priority]||a.result.score-b.result.score);if(!options.length)break;excluded.push(options[0].item.id);result=options[0].result;}return {candidates,excluded,result,blocked:result.score>target};}
root.PromoEngine={defaultConfig,calculate,rating,suggestions,intersect};if(typeof module!=='undefined')module.exports=root.PromoEngine;
})(typeof window!=='undefined'?window:globalThis);
